In [ ]:
from numpy import arange
import matplotlib.pyplot as plt
from matplotlib.colors import LogNorm
import pandas as pd
import seaborn as sns

f_appr = 193.405059 * 1e12

fr_m = 1e8 + 122.793
fb_m = -40e6
f0_m = -35e6

fr_l = 1e8 + 14.208 
fb_l = -30e6
f0_l = -35e6

n_appr_m = round((f_appr - f0_m - fb_m) / fr_m)
n_appr_l = round((f_appr - f0_l - fb_l) / fr_l)

search_range = arange(-1000,1000)

freqs = []
for n_m in n_appr_m + search_range:
    for n_l in n_appr_l + search_range:
        f_cw_m = n_m * fr_m + fb_m + f0_m
        f_cw_l = n_l * fr_l + fb_l + f0_l
        f_diff = abs(f_cw_m - f_cw_l)
        f_min = min(f_cw_m, f_cw_l) 
        freqs.append((n_m, n_l, f_cw_m, f_cw_l, f_diff, f_min))

df = pd.DataFrame(freqs, columns=['Mikey Mode',
                                  'Leo Mode',
                                  'Mikey CW Calc',
                                  'Leo CW Calc',
                                  'Frequency Diff',
                                  'Frequency Min'])

df.sort_values(by='Frequency Diff')[:5]
# pivot = df.pivot(index='Mikey Mode', columns='Leo Mode', values='Frequency Diff')
# sns.heatmap(pivot, norm=LogNorm())
# plt.xlabel('Mikey Mode')
# plt.ylabel('Leo Mode')
# plt.title('Predicted CW Frequency Difference')
# plt.show()

,Mikey Mode,Leo Mode,Mikey CW Calc,Leo CW Calc,Frequency Diff,Frequency Min
1840920,1933969,1933971,1.933971e+14,1.933971e+14,4.56250,1.933971e+14
1842921,1933970,1933972,1.933972e+14,1.933972e+14,104.03125,1.933972e+14
1838919,1933968,1933970,1.933970e+14,1.933970e+14,113.15625,1.933970e+14
1844922,1933971,1933973,1.933973e+14,1.933973e+14,212.59375,1.933973e+14
1836918,1933967,1933969,1.933969e+14,1.933969e+14,221.75000,1.933969e+14

In [5]:
from numpy import arange
import matplotlib.pyplot as plt
from matplotlib.colors import LogNorm
import pandas as pd
import seaborn as sns

f_appr = 193.405059 * 1e12

fr_m = 1e8 + 122.795
fb_m = -40e6
f0_m = -35e6

fr_l = 1e8 + 34.895
fb_l = 30e6
f0_l = -35e6

n_appr_m = round((f_appr - f0_m - fb_m) / fr_m)
n_appr_l = round((f_appr - f0_l - fb_l) / fr_l)

search_range = arange(-1000,1000)

freqs = []
for n_m in n_appr_m + search_range:
    for n_l in n_appr_l + search_range:
        f_cw_m = n_m * fr_m + fb_m + f0_m
        f_cw_l = n_l * fr_l + fb_l + f0_l
        f_diff = abs(f_cw_m - f_cw_l)
        f_min = min(f_cw_m, f_cw_l) 
        freqs.append((n_m, n_l, f_cw_m, f_cw_l, f_diff, f_min))

df = pd.DataFrame(freqs, columns=['Mikey Mode',
                                  'Leo Mode',
                                  'Mikey CW Calc',
                                  'Leo CW Calc',
                                  'Frequency Diff',
                                  'Frequency Min'])

df.sort_values(by='Frequency Diff')
# pivot = df.pivot(index='Mikey Mode', columns='Leo Mode', values='Frequency Diff')
# sns.heatmap(pivot, norm=LogNorm())
# plt.xlabel('Mikey Mode')
# plt.ylabel('Leo Mode')
# plt.title('Predicted CW Frequency Difference')
# plt.show()

,Mikey Mode,Leo Mode,Mikey CW Calc,Leo CW Calc,Frequency Diff,Frequency Min
1934967,1934016,1934017,1.934018e+14,1.934018e+14,2.850000e+01,1.934018e+14
1936968,1934017,1934018,1.934019e+14,1.934019e+14,5.943750e+01,1.934019e+14
1932966,1934015,1934016,1.934017e+14,1.934017e+14,1.163750e+02,1.934017e+14
1938969,1934018,1934019,1.934020e+14,1.934020e+14,1.473125e+02,1.934020e+14
1930965,1934014,1934015,1.934016e+14,1.934016e+14,2.042812e+02,1.934016e+14
...,...,...,...,...,...,...
1998,1933049,1935048,1.933051e+14,1.935049e+14,1.998002e+11,1.933051e+14
3996000,1935047,1933050,1.935049e+14,1.933051e+14,1.998002e+11,1.933051e+14
3998001,1935048,1933051,1.935050e+14,1.933052e+14,1.998002e+11,1.933052e+14
1999,1933049,1935049,1.933051e+14,1.935050e+14,1.999002e+11,1.933051e+14
3998000,1935048,1933050,1.935050e+14,1.933051e+14,1.999002e+11,1.933051e+14

In [8]:
from numpy import arange
import matplotlib.pyplot as plt
from matplotlib.colors import LogNorm
import pandas as pd
import seaborn as sns

f_appr = 193.405059 * 1e12

fr_m = 1e8 + 2087.626
fb_m = -40e6
f0_m = -35e6

fr_l = 1e8 + 34.895
fb_l = 30e6
f0_l = -35e6

n_appr_m = round((f_appr - f0_m - fb_m) / fr_m)
n_appr_l = round((f_appr - f0_l - fb_l) / fr_l)

search_range = arange(-1000,1000)

freqs = []
for n_m in n_appr_m + search_range:
    for n_l in n_appr_l + search_range:
        f_cw_m = n_m * fr_m + fb_m + f0_m
        f_cw_l = n_l * fr_l + fb_l + f0_l
        f_diff = abs(f_cw_m - f_cw_l)
        f_min = min(f_cw_m, f_cw_l) 
        freqs.append((n_m, n_l, f_cw_m, f_cw_l, f_diff, f_min))

df = pd.DataFrame(freqs, columns=['Mikey Mode',
                                  'Leo Mode',
                                  'Mikey CW Calc',
                                  'Leo CW Calc',
                                  'Frequency Diff',
                                  'Frequency Min'])

df.sort_values(by='Frequency Diff')[:5]
# pivot = df.pivot(index='Mikey Mode', columns='Leo Mode', values='Frequency Diff')
# sns.heatmap(pivot, norm=LogNorm())
# plt.xlabel('Mikey Mode')
# plt.ylabel('Leo Mode')
# plt.title('Predicted CW Frequency Difference')
# plt.show()

,Mikey Mode,Leo Mode,Mikey CW Calc,Leo CW Calc,Frequency Diff,Frequency Min
1998999,1934010,1934049,1.934050e+14,1.934050e+14,920.40625,1.934050e+14
1996998,1934009,1934048,1.934049e+14,1.934049e+14,1132.31250,1.934049e+14
2001000,1934011,1934050,1.934051e+14,1.934051e+14,2973.12500,1.934051e+14
1994997,1934008,1934047,1.934048e+14,1.934048e+14,3185.06250,1.934048e+14
2003001,1934012,1934051,1.934052e+14,1.934052e+14,5025.90625,1.934052e+14